defaults:
  - _self_
  - experiment: base

data:
  dataset: mnist
  subset_size: 10000
  batch_size: 64

training:
  epochs: 15
  learning_rate: 0.0003
  device: cuda
  patience: 5

model:
  type: base
  hidden_size: 128