defaults:
  - _self_
  - experiment: base

data:
  dataset: mnist
  subset_size: 10000
  batch_size: 64
  train_val_split: 0.8  # 80% train, 20% validation
  num_classes: 10  # MNIST has 10 classes (change this accordingly)

training:
  epochs: 15
  learning_rate: 0.0003
  device: cuda
  patience: 5

model:
  type: base
  hidden_size: 128
  dropout: 0.0
