defaults:
  - _self_
  - experiment: base  # Default to base experiment
  - override hydra/launcher: joblib

data:
  dataset: mnist
  subset_size: 10000
  batch_size: 64
  train_val_split: 0.8  # 80% train, 20% validation
  num_classes: 10  # MNIST has 10 classes (change this accordingly)

training:
  epochs: 15
  learning_rate: 0.0003
  device: cuda
  patience: 5

# config/experiment/base.yaml
model:
  type: models.BaseModel
  hidden_size: 128
  dropout: 0.0

# config/experiment/experiment.yaml
model:
  type: models.ExperimentModel
  hidden_size: 256
  dropout: 0.5
